### ISSUE TITLE
implement return value from callback for Java/JNI

### ISSUE THREAD

**Issue by Dushistov** [Dushistov/flapigen-rs#195]

**Comment by Kofituo** [comment]
Any update on this issue. I'm facing a similar problem

**Comment by Dushistov** [comment]
@Kofituo 

I partly implemented this feature. Not all cases are covered, but for `bool` return type all should work just fine.
I will push it to master in the near future.

**Comment by Kofituo** [comment]
@Dushistov 
I get a not implemented error when returning the `bool` type

**Comment by Dushistov** [comment]
@Kofituo 

It should work just fine with current master, see https://github.com/Dushistov/flapigen-rs/blob/fa3cd2c4d411f7e1eab7e0c17357a1d8a918c9b2/jni_tests/src/java_glue.rs.in#L1055

Make sure that you use commit fa3cd2c4d411f7e1eab7e0c17357a1d8a918c9b2

**Comment by Dushistov** [comment]
@Kofituo 

it should be something like:
```
flapigen = { git = "https://github.com/Dushistov/flapigen-rs", rev = "fa3cd2c4d411f7e1eab7e0c17357a1d8a918c9b2 " }
```
in your Cargo.toml

**Comment by Kofituo** [comment]
Okay I'll try that and get back to you

**Comment by Kofituo** [comment]
Yep it works thanks
