### ISSUE TITLE
foreign_callback! / to_c_interface pointer questions

### ISSUE THREAD

**Issue by xv-matt-u** [Dushistov/flapigen-rs#273]
1. Unclear what the lifetime of `c_class` should be - is it safe to deallocate `c_class` once `call_me` has returned?:

```c++
auto obs = new MySomeObserver;
//...
auto c_class = SomeObserver::to_c_interface(obs);
Foo::call_me(&c_class);
```

2. Seeing as `to_c_interface` essentially takes ownership, what about hiding the C interface by using `std::unique_ptr`? I imagine from the user's point of view it could look like this:

```c++
Foo::call_me(std::make_unique<MySomeObserver>());
```

Assuming the pointer to `c_class` only needs to be valid until `call_me` returns, under the hood presumably something like this (it can be nicer but this fits closer to current code):
```c++
void Foo::call_me(std::unique_ptr<SomeObserver> observer) {
  auto c_class = SomeObserver::to_c_interface(observer.release());
  call_me(&c_class);
}

static void c_SomeObserver_deref(void* opaque) {
  std::unique_ptr<SomeObserver> death{static_cast<SomeObserver*>(opaque)};
}
```

**Comment by Dushistov** [comment]
@xv-matt-u 

> Unclear what the lifetime of c_class
> Seeing as to_c_interface essentially takes ownership

Yes, allocated memory in your code `auto obs = new MySomeObserver;` will indirectly owned by Rust,
and freed when `Box<Trait>` will be dropped inside Rust code.

> what about hiding the C interface by using std::unique_ptr

This is for historical reasons, when the API was designed, it would be too hard to implement,
now with new infrastructure for describing C++<->Rust type conversation it is much more simple to implement, but I have not had time to implement this feature.
