### ISSUE TITLE
Java hashCode implementation

### ISSUE THREAD

**Issue by giarc3** [Dushistov/flapigen-rs#302]
I am using rust_swig to generate Java for my classes. I need to be able to check equality between instances of the class in Java, so I need to override their `.hashCode` and `.equals` functions. Normally there are code generators to do this, but they do not work for the Java being generated. Do you know of an easy way to implement these functions for the generated classes?

**Comment by Dushistov** [comment]
@giarc3 

> Normally there are code generators to do this, but they do not work for the Java being generated. Do you know of an easy way to implement these functions for the generated classes?

For now you have to add to each class this manualy:

```rust
foreign_class!(
class Foo {
self_type Foo;
constructor Foo::new(val: i32, name: &str) -> Foo;
...
foreign_code r#"
  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof Foo)
      equal = (((Foo)obj).mNativeObj == this.mNativeObj);
    return equal;
  }
  public int hashCode() {
     return (int)mNativeObj;
  }
"#;
);
```

I will think about how to automate this in the future release.

**Comment by giarc3** [comment]
Thank you for the quick response. 
A solution like you posted would be great, as I'm currently forced to implement something like: 
```    
public boolean equals(Object obj) {
        if(obj instanceof PolicyGrant){
            PolicyGrant pg = (PolicyGrant) obj;
            return pg.getCategory().equals(this.getCategory()) &&
            pg.getSensitivity().equals(this.getSensitivity()) &&
            pg.getDataSubject().equals(this.getDataSubject()) &&
            pg.getSubstituteId().equals(this.getSubstituteId());
        }
        return false;
    }
```
Unfortunately, what I am looking for is content comparison, and I believe the code you posted is for address comparison. That is, I want two instances of the object which both hold the same information to be considered equal. 
Do you have any suggestions or ways to achieve this without my current manual implementation?

**Comment by Dushistov** [comment]
@giarc3 

> That is, I want two instances of the object which both hold the same information to be considered equal

You can just use your Rust "equal" implementation directly (I mean `PartialEq` trait):

```rust
#[derive(PartialEq)]//!<--- so just generate eq method automatically
struct Foo { ... }

foreign_class!(
class Foo {
    self_type Foo;                                                                                                                                            
    constructor ...;
    
    private fn Foo::eq(&self, o: &Foo) -> bool; alias rustEq;
foreign_code r#"                                                                                                                                                                                            
  public boolean equals(Object obj) {                                                                                                                                                                       
    boolean equal = false;                                                                                                                                                                                  
    if (obj instanceof Foo)                                                                                                                                                                                 
      equal = ((Foo)obj).rustEq(this);                                                                                                                                                                      
    return equal;                                                                                                                                                                                           
  }                                                                                                                                                                                                         
  public int hashCode() {                                                                                                                                                                                   
     return (int)mNativeObj;                                                                                                                                                                                
  }                                                                                                                                                                                                         
"#;
});

```

**Comment by giarc3** [comment]
That's an excellent solution. Thank you very much!

**Comment by giarc3** [comment]
Using this implementation, all of my foreign_classes have very similar implementations for `equals` and `hashCode`, with the only difference being the class name. I would like to be able to use a declarative macro to avoid copying code, but I believe that the java expansion is done by the build script before macro expansion, causing it to fail compiling. Is that correct? 
Do you know of a way that I could make the macros expand before attempting to generate the java code?

**Comment by Dushistov** [comment]
> Do you know of a way that I could make the macros expand before attempting to generate the java code?

I suppose you can do it, but it would be much of efforts.
There is other way I suppose. You can just write a little of Rust code.
You still need add `fn Foo::eq` to `foreign_class` manually,
but all other things you can generate. Just add code after `rust_swig::Generator::expand` to traverse all Java generated code and add suitable functions into java files.

**Comment by Dushistov** [comment]
In future I may be add some extension point for rust swig, like
```
foreign_class!(
#[derive(RustSwigClassExtension)] //<--- HERE
class Foo {
...
```
and in `build.rs` you can register callback with name `RustSwigClassExtension`,
that recieve class info (like name, methods lists and so on),
so you add some code into generated code with less efforts,
but this design need more thought.

**Comment by Dushistov** [comment]
I implement rough interface for this https://github.com/Dushistov/flapigen-rs/blob/473bd3d5cc809005dd440a13e2c54b293327d706/jni_tests/build.rs#L35
