### ISSUE TITLE
Are type parameters supported?

### ISSUE THREAD

**Issue by Josef-Vonasek** [Dushistov/flapigen-rs#327]
I have been reading trough documentation, but there is not mention of generic type parameters anywhere.

What I would like is to convert the following rust code:

```rust
pub struct Foo<T>(t:T);

impl<T> Foo<T> {
  pub fn new(t:T) -> Self { Foo(t) }
}
```
Into:
```java
class Foo<T> {
  public T t
  public Foo<String>(String t) { this.t = t }
  public Foo<Int>(Int t) { this.t = t}
}
```
But it seems that the `foreign_class` macro does not support type parameters in `class`, nor overloaded constructors.

Am I missing something?

**Comment by Dushistov** [comment]
Ovearload constructors definitely supported,
I mean constructors with different types of parameters, different number of parameters and so on:
for example: https://github.com/Dushistov/flapigen-rs/blob/3c1ddfb87b055081d1fa9987faf9e16427ce1a5e/jni_tests/src/java_glue.rs.in#L242

Generics in `foreign_class` is not supported. So you have to specify exact specilazation that 
you plan to export like:
```
pub struct Foo<T> {
    t: T,
}

impl<T> Foo<T> {
    pub fn new(t: T) -> Self {
        Self { t }
    }
}

type FooI32 = Foo<i32>;

foreign_class!(class Foo {
    self_type FooI32;

    constructor FooI32::new(_: i32) -> FooI32;
});
```

There are way to map generic Rust types to corresponding "foreign language" mechanism,
but it is more complex then `foreign_class`, for example
https://github.com/Dushistov/flapigen-rs/blob/3c1ddfb87b055081d1fa9987faf9e16427ce1a5e/macroslib/src/java_jni/jni-include.rs#L434

**Comment by Josef-Vonasek** [comment]
Could you please document somewhere how `foreign_typemap!` works (what code does it produce)? It's not immediately obvious from the example.

**Comment by Dushistov** [comment]
`foreign_typemap!` is intentionally undocumented, because of it's syntax is still changing.
But I will think about adding some minimal of documentation.

**Comment by Dushistov** [comment]
https://dushistov.github.io/flapigen-rs/foreign-typemap.html
