### ISSUE TITLE
Make it possible to ignore return type when declaring functions

### ISSUE THREAD

**Issue by tasn** [Dushistov/flapigen-rs#335]
I'm not sure if what I'm suggesting is desirable or not, and it's sort of related to #329: though now, in order to ignore the return value in the API (e.g. if you don't want to expose it), you have to wrap the function in a new function.
You can't even have the function inline (because you can't use self in those), so you end up having to write a whole new function when you just want to ignore the return value.
Example:
```
pub struct User {
    username: String,

}

impl User {
    // ...
    pub fn set_username(&mut self, username: &str) -> &mut Self {
        self.username = username.to_owned();
        self
    }
}

foreign_class!(class User {
    self_type User;
    constructor User::new(username: &str, email: &str) -> User;
    fn User::set_username(&mut self, username: &str);
}
```
Will fail with:
```
     |
1486 |     let mut ret: () = User::set_username(this, username);
     |                  --   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found `&mut etebase::online_managers::User`
     |                  |
     |                  expected due to this

```

**Comment by Dushistov** [comment]
In inline function you can use special variable `this`:
```
foreign_class!(class User {
    self_type User;
    constructor User::new(username: &str, email: &str) -> User;
    fn setUsername(&mut self, username: &str) {
        this.set_username(username);
    }
});
```

**Comment by tasn** [comment]
Yea thanks, I found it out by digging through the code a bit, though was wondering if this is something I can rely upon, especially across different targets (C++, Java, etc).
Anyhow, thanks, I'm closing this, now that I know it's something I can actually rely on existing. Maybe it's worth changing it to `self_` and having it always be defined for every backend?

Anyhow, thanks a lot, feel free to close this ticket once you've read the `self_` comment.

**Comment by Dushistov** [comment]
I added notion about `this` into https://dushistov.github.io/flapigen-rs/foreign-class.html#inline-methods , it should work across all languages.

**Comment by tasn** [comment]
Great, thanks!

Python doesn't seem to support inline functions, so it doesn't work there. :|
