### ISSUE TITLE
Enhancement: add support for `protected` for functions (in Java)

### ISSUE THREAD

**Issue by tasn** [Dushistov/flapigen-rs#344]
Hey,

I'm trying to implement a workaround for #329 and I settled on something like this:
```java
foreign_class!(class FetchOptions {
    self_type FetchOptions;
    constructor FetchOptions::new() -> FetchOptions;

    fn FetchOptions::prefetch(&mut self, prefetch: PrefetchOption); alias __prefetch;
   
    foreign_code r#"
    public final FetchOptions prefetch(PrefetchOption prefetch) {
        this.__prefetch(prefetch);
        return this;
    }
"#;
});
```

Though my problem is that __prefetch is generated as public. I saw in the flapigen sources that there are `private` and `protected` keywords though they are not implemented for Java it seems? Is this something that's hard to add?

Thanks,
Tom

**Comment by Dushistov** [comment]
> keywords though they are not implemented for Java it seems?

`private` keyword should works just fine, `protected` is not implemented.
I suppose I missed that there is such keyword in Java.

**Comment by tasn** [comment]
How do I mark a function as private? I haven't managed to figure it out (tried a few combinations). I only managed to get it to work for constructors.

Thanks!

**Comment by tasn** [comment]
Nevermind, I take it back. I haven't tried `private fn` it seems. I tried omitting the fn, like is done for constructors. It works.

**Comment by tasn** [comment]
Thanks a lot!

**Comment by Dushistov** [comment]
> Nevermind, I take it back.

You misunderstanding  hint me that I actually do not document this,
should be fixed now:

https://dushistov.github.io/flapigen-rs/foreign-class.html#access-modifiers

**Comment by tasn** [comment]
Thanks a lot, makes the difference! I'm sorry again for opening so many tickets, it's just such a great project, so I want to help, even if my ability is limited to only reporting issues I'm encountering. Thanks a lot for this!
