### ISSUE TITLE
Java: typemap returns a @Nullable value but doesn't include the necessary import

### ISSUE THREAD

**Issue by tasn** [Dushistov/flapigen-rs#346]
Hey,

I have a function returning an `Option<&str>` for which I use this typemap (almost identical to the `Option<String>` one, only difference is the `to_owned()`):
```rust
foreign_typemap!(
    ($p:r_type) Option<&str> => internal_aliases::JStringOptStr {
        $out = match $p {
            Some(s) => from_std_string_jstring(s.to_owned(), env),
            None => ::std::ptr::null_mut(),
        };
    };
    ($p:f_type, option = "NoNullAnnotations") => "java.util.Optional<String>" r#"
        $out = java.util.Optional.ofNullable($p);
"#;
    ($p:f_type, option = "NullAnnotations") => "@NonNull java.util.Optional<String>" r#"
        $out = java.util.Optional.ofNullable($p);
"#;
);
```
It works correctly, though the only problem is that @Nullable is not being imported. It is being imported in other classes (which use `Option<String>` as a function parameter, so I think there's a bug with return types not triggering the import of `@Nullable`.

Adding this to the class fixes the issue:
```rust
fn fix_nullable_import(_value: Option<&str>) {
}
```

**Comment by Dushistov** [comment]
I tried this:

```
foreign_class!(
    class ReturnNullableValue {
        fn getOpt() -> Option<String>;
    }
);
```

```
package org.example;
import android.support.annotation.NonNull;

public final class ReturnNullableValue {

    public static @NonNull java.util.Optional<String> getOpt() {
        String ret = do_getOpt();
        java.util.Optional<String> convRet = java.util.Optional.ofNullable(ret);

        return convRet;
    }
    private static native @Nullable String do_getOpt();

    private ReturnNullableValue() {}
}
```

```
import android.support.annotation.NonNull;
```

is in place.

**Comment by Dushistov** [comment]
Can you provide more full test case, so I can able to reproduce?

**Comment by tasn** [comment]
`@NonNull` is not the problem, the problem is only `@Nullable`.
Also, the example you just pasted here is broken and won't compile! You have:
```java
    private static native @Nullable String do_getOpt();
```
But `@Nullable` is never being imported, that's exactly what I'm talking about. :)


It seems like you already managed to reproduce it, but here's the code I'm using in case you still want it: https://github.com/etesync/etebase-java
I added the workaround to the broken classes so they are easy to spot.

**Comment by Dushistov** [comment]
My bad, I somehow missed `do_getOpt`

**Comment by tasn** [comment]
Yay, thanks!
