### ISSUE TITLE
Java: inconsistency with converting `Option<T>` to `Nullable` vs `Optional`

### ISSUE THREAD

**Issue by tasn** [Dushistov/flapigen-rs#347]
Hey,

I'm still using my codebase here: https://github.com/etesync/etebase-java
I've just hit an inconsistency issue
```rust
    private fn FetchOptions::stoken(&mut self, stoken: Option<&str>); alias _stoken;
```
This function accepts a @Nullable String.
While this function returns an Optional:
```rust
    fn Collection::stoken(&self) -> Option<&str>; alias getStoken;
```
(again, I'm using an essentially identical rule to `Option<String>`)
This inconsistency is confusing, but more than that, it's incompatible. You can't take the value returned from the second and use it in the first because of it, not without an extra adjustment.

To be honest, I don't even want `Optional`. It doesn't work that well with Kotlin (which has its optional based on nullability) and I really just want to turn it off. Is there a way to do it? Edit: I just changed my typemaps to remove any mention of Optional.

Thanks,
Tom

**Comment by Dushistov** [comment]
This is based on https://stackoverflow.com/questions/31922866/why-should-java-8s-optional-not-be-used-in-arguments ,
in other way from my opinion there is consensus in Java world that `java.util.Optional` should be used only for return argument.

**Comment by tasn** [comment]
Gotcha, OK, let's close this then. Sorry for the noise.
