### ISSUE TITLE
Accept Nullable as Option<&str> or Option<String> parameters for traits

### ISSUE THREAD

**Issue by Kofituo** [Dushistov/flapigen-rs#352]
Is there a way to accept Nullable String as Optional parameter for a trait method? It seems it's allowed for normal structs but not for traits

**Comment by Dushistov** [comment]
Looks like duplicate to #332 .
The solution is: https://github.com/Dushistov/flapigen-rs/issues/332#issuecomment-665577369 ,
feel free to ask question in #332 if something not clear.
