### ISSUE TITLE
Why I need a 'boost'?

### ISSUE THREAD

**Issue by hanusek** [Dushistov/flapigen-rs#390]
Hello!

"To run cpp-example from here you need boost, cmake and C++11 compatible compiler."

"It is normal CMake project, so you can build as ordinary CMake project. By default it requires C++11 and boost, but if your compiler is modern enough you can use C++17 and then you no need boost at all."

Can I use:
https://en.cppreference.com/w/cpp/utility/optional  ?
The library will translate Rust::Optional to Cxx::Optional?

**Comment by Dushistov** [comment]
> Can I use:
> https://en.cppreference.com/w/cpp/utility/optional

`std::optional` is part of C++17 standard. So if you have C++17 compatible compiler you can obviously use c++17 mode without boost, as mentioned in quote:

> It is normal CMake project, so you can build as ordinary CMake project. By default it requires C++11 and boost, but if your compiler is modern enough you can use C++17 and then you no need boost at al
