### ISSUE TITLE
Insert raw code into generated Class

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [Dushistov/flapigen-rs#391]
I'm fairly new to this tool and I'm integrating flapigen to generate binds for Android of a Rust library I develop and I was wondering the following:

Does the tool have some support for inserting raw code (e.g. attributes and a method) into the resulting Java class it generates?

I need some Java code initialization in order to use my Rust library that I wanna pack into the library I provide to make the public API easier to use.

**Comment by Dushistov** [comment]
Yes, there is foreign_code, see documentation: https://dushistov.github.io/flapigen-rs/foreign-class.html#foreigner_code

**Comment by Jonathas-Conceicao** [comment]
That's quite what I needed, I must have missed it when looking trough the docs. Thanks for the help :smile:
