### ISSUE TITLE
Is there direct support for conditional compilation?

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [Dushistov/flapigen-rs#405]
When I create a `foreign_class!` can I specify that some code segment is only generated for a specified target?

Something like:
```Rust
    #[cfg(not(target_os = "android"))]
    foreign_code "some_foreign_code"
```
Seems to have no effect.

I suppose I can put the hole `foreign_class!` inside a conditional compilation _attribute_. But is there a way to do this without duplicating code?

**Comment by Dushistov** [comment]
Only `#[cfg(target_pointer_width = "X")]` is supported. But you can move platfrom specific
class to separate file (https://docs.rs/flapigen/0.6.0-pre7/flapigen/struct.Generator.html#method.expand_many) and use
```rust
if cfg!() {
```
in you `build.rs` to include or exclude this `file.rs.in` from handling via `flapigen`

**Comment by Jonathas-Conceicao** [comment]
Ok, got it. But in my case I actually have a big class with a single function (on a foreign_code) that is platform specific.

Is that a way to add code to a class outside of it's `foreign_class` definition?

**Comment by Dushistov** [comment]
You can register special attribute handlers via [register_method_attribute_callback](https://docs.rs/flapigen/0.6.0-pre7/flapigen/struct.Generator.html#method.register_method_attribute_callback) or  [register_class_attribute_callback](https://docs.rs/flapigen/0.6.0-pre7/flapigen/struct.Generator.html#method.register_class_attribute_callback) . And make method private in case if it is wrong platform, or just remove the whole method if it is suitable for platfrom.

And obviously you can just use file I/O in build.rs to modify code after flapigen finish its job.

**Comment by Jonathas-Conceicao** [comment]
In my case I was trying to guard code that wen't on java's class static initialization block. I just ended up solving this inside the foreign_code itself, seamed easier to solve it this way.

Thanks for the help.
