### ISSUE TITLE
Question : bindings conditional generation

### ISSUE THREAD

**Issue by stephan57160** [Dushistov/flapigen-rs#429]
I'm trying to use a unique set of `foreign_class!()` to generate the bindings of the same library, 
but for diffferent languages (cpp, java, python, ...).

I wonder if there is any possible conditional code generation, like :
``` 
foreign_class!(class Foo {
  fn function_avail_anywhere();

  #[cfg(not(xxx  = yyy))]
  fn function_not_avail_with_option_yyy();

  #[cfg(xxx  = yyy)]
  fn function_avail_with_option_yyy();
}
```

**Comment by Dushistov** [comment]
No, embedded into flapigen parser as simple as possible, it catch only "doc" attributes as I remember.

**Comment by stephan57160** [comment]
OK. Thx to confirm.

Tried also something like 
```
#[cfg(xxx === yyy)
foreign_class!(class Foo) {
...
}
```
but does not work...
